 name: gestion_medicament
 description: "A new Flutter project."
 publish_to: 'none'

 version: 1.0.0+1

 environment:
  sdk: ^3.6.2

 dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+4
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.11
  provider: ^6.0.0
  intl: ^0.18.0
  path: ^1.9.0  # تمت إضافة حزمة path هنا
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.1.0




 dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

 flutter:
   uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
